apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: 5ds
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: mzago/backend
        resources:
          limits:
            memory: "356Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  namespace: 5ds
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer
