name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract version number
      id: version
      run: |
        # Extract the version number from git describe
        VERSION_TAG=$(git describe --tags --abbrev=0)
        # If there are additional commits or the working directory is dirty, append extra info
        if [ -z "$VERSION_TAG" ]; then
          VERSION_TAG="0.0.0"
        fi
        echo "::set-output name=tag::$VERSION_TAG"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: mzago/backend:latest, mzago/backend:${{ steps.version.outputs.tag }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: mzago/frontend:latest, mzago/frontend:${{ steps.version.outputs.tag }}
